test:
  adapter: mysql2
  encoding: utf8
  database: template_api_development
  pool: 5
  host: localhost
  username: root
  password:

development:
  adapter: mysql2
  encoding: utf8
  database: template_api_development
  pool: 5
  host: localhost
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  database: template_api_production
  pool: 5
  host: localhost
  username: root
  password: 